[build]
compiler = "g++"
build_dir = "./bin"
obj_dir = "./obj_lin"

[[targets]]
name = "libengine"
src = "./Engine/src/"
include_dir = "./Engine/src/include"
type = "dll"
cflags = "-g -Wall -Wunused `pkg-config --cflags freetype2` -std=c++17"
libs = "-lm -lGL -lGLEW -lglfw `pkg-config --libs freetype2`"

[[targets]]
name = "main"
src = "./Game/src/"
include_dir = "./Game/src"
type = "exe"
cflags = "-g -Wall -IEngine/src/include"
libs = " -Lbin -lengine -Wl,-rpath=bin"
